### ISSUE TITLE
Dockerfile doesn't use the last version of the script provided in tmp.

### ISSUE THREAD

**Issue by zallek** [botify-labs/contest#2]
I don't understand why, but the doker container seems to not use the given code file or use the one present when creating docker container I don't know.

**Comment by zallek** [comment]
Modify the file in `tmp/test.js`.
Launch `docker run -ti -v $(pwd)/tmp:/contest botify/contest/js sh`
the file in the container at `/contest/test.js` didn't changed

**Comment by jbbarth** [comment]
Discussed on Slack, the base alpine image is buggy regarding volumes when used through virtualbox/boot2docker => https://github.com/gliderlabs/docker-alpine/issues/41 ; switching to ubuntu would solve the problem.

Also _not_ using a volume would probably work too, == passing the data via stdin.
